### PR TITLE
fix(lib): update config types

### PR DESCRIPTION
**Pull request by Lichthagel**
Updated the types according to https://github.com/spicetify/spicetify-cli/blob/43c3b8b97a960f80af684912233722a2c38bad92/src/utils/config.go#L14 (and also copied the ordering)

### CODE REVIEW

**Comment by Gerg-L** [comment]
Thanks for contributing, that was the next thing I was going to mess with lol, I'll take a look tomorrow probably

**Comment by Lichthagel** [comment]
Well, best solution would be to generate types automatically or some other way to keep them in sync in the future.

**Comment by Gerg-L** [comment]
hmmm yeah, https://github.com/Gerg-L/spicetify-nix/blob/2c285ab994ace0784c0dd8c87637f0271ec0cf40/module.nix#L80-L107 also needs updated

**Comment by Gerg-L** [comment]
alright lets see if this breaks stuff lol

**Pull request merged**
